/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author crYptONE
 */
public class profile extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    String nikaaa = db.javasession.get_Nik();
    String namaaaa = db.javasession.get_Nama();

    /**
     * Creates new form profile
     */
    public profile() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        nika.requestFocus();
        
        setDefaultTable();
        conn = db.koneksi.koneksi();
        String query = "SELECT * FROM tb_pengguna WHERE nik=?";
        try {
            pst = conn.prepareStatement(query);
            pst.setString(1, nikaaa);
            rs = pst.executeQuery();
            while (rs.next()){
                
                nika.setText(nikaaa);
                nama.setText(namaaaa);
               almt.setText(rs.getString("alamat"));
               jenkel.setSelectedItem(rs.getString("jenkel"));
               
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    String data[]=new String[5];
    public void setDefaultTable() {
        try{
            String hubung = "jdbc:mysql://localhost:3306/cttjalan";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String nik = nika.getText();
            String SQL = "select * from tb_pengguna where nik like'"+nik+"'";
            ResultSet res = stt.executeQuery(SQL);
        while(res.next()){
            data[0] = res.getString(1);
            data[1] = res.getString(2);
            data[2] = res.getString(3);
            data[3] = res.getString(4);
            data[4] = res.getString(5);
        }
            res.close();
            stt.close();
            kon.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
            JOptionPane.showMessageDialog(null, "Data Tidak ditemukan");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nika = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        almt = new javax.swing.JTextArea();
        jenkel = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(470, 650));
        getContentPane().setLayout(null);

        nika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikaActionPerformed(evt);
            }
        });
        getContentPane().add(nika);
        nika.setBounds(190, 120, 230, 40);
        getContentPane().add(nama);
        nama.setBounds(190, 170, 230, 40);

        almt.setColumns(20);
        almt.setRows(5);
        jScrollPane1.setViewportView(almt);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 220, 230, 150);

        jenkel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenis Kelamin", "Laki - Laki", "Perempuan" }));
        getContentPane().add(jenkel);
        jenkel.setBounds(250, 390, 150, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/9.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 470, 650);

        ubah.setText("jButton1");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah);
        ubah.setBounds(220, 560, 110, 60);

        hapus.setText("jButton1");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(340, 0, 110, 50);

        kembali.setText("jButton1");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali);
        kembali.setBounds(340, 560, 100, 60);

        setBounds(0, 0, 470, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void nikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nikaActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        try {
            Object[]options = {"YA","TIDAK"};
            int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Ingin Ubah Data?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
            if(konfirmasi==JOptionPane.YES_OPTION) {

                String hubung = "jdbc:mysql://localhost:3306/cttjalan";
                    Class.forName("com.mysql.jdbc.Driver").newInstance();
                    Connection kon = DriverManager.getConnection(hubung,"root","");
                    Statement stt = kon.createStatement();
                    String SQL = "update tb_pengguna set nik = '"+nika.getText()+"',"+"nama='"+nama.getText()+"',"+"alamat='"+almt.getText()+"',"+"jenkel='"+jenkel.getSelectedItem()+"' where nik = '"+nika.getText()+"'";
                     stt.executeUpdate(SQL);
                 data[0] = nika.getText();
                 data[1] = nama.getText();
                 data[2] = almt.getText();
                 data[3] = jenkel.getSelectedItem().toString();
                 
                  stt.close();
                  kon.close();
                
            }

        } catch (Exception exc) {
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        menu inf = new menu();
        inf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:   
        try {
            Object[]options = {"YA","TIDAK"};
            int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Ingin Hapus Data?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
            if(konfirmasi==JOptionPane.YES_OPTION) {
                
                String hubung = "jdbc:mysql://localhost:3306/cttjalan";
                    Class.forName("com.mysql.jdbc.Driver").newInstance();
                    Connection kon = DriverManager.getConnection(hubung,"root","");
                    Statement stt = kon.createStatement();
                    String SQL = "delete from tb_pengguna where nik='"+nika.getText()+"'";
                    String sol = "delete from tb_catatan where nik='"+nika.getText()+"'";
                    stt.executeUpdate(SQL);
                    stt.executeUpdate(sol);
                 data[0] = nika.getText();
                 data[1] = nama.getText();
                 data[2] = almt.getText();
                 data[3] = jenkel.getSelectedItem().toString();
            stt.close();
            kon.close();
            
        login inf = new login();
        inf.setVisible(true);
        this.dispose();
        
                }
            
        } catch (Exception exc) {
        }
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea almt;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenkel;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nika;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
